/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionprestamos;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import com.mycompany.views.*;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;

/**
 *
 * @author lizet
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        InitStyles();
        SetDate();
        InitContent();
    }

    private void InitStyles() {
        textHeader.putClientProperty("FlatLaf.styleClass", "h2");
        dateHeader.putClientProperty("FlatLaf.styleClass", "h1");
        inicio.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
        prestamos.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
        devoluciones.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
        usuarios.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
        libros.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
        reportes.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
    }

    private void InitContent() {
        ShowJPanel(new Inicio());
    }

    private void ShowJPanel (JPanel p1){
        p1.setSize(780,430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    private void SetDate() {
        // Obtener la fecha actual
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");

        // Formatear la fecha según el patrón deseado
        String formattedDate = now.format(DateTimeFormatter.ofPattern("EEEE, dd 'de' MMMM 'de' yyyy", spanishLocale));

        // Obtener las partes de la fecha
        String dayPart = formattedDate.substring(0, formattedDate.indexOf(" de "));
        String monthPart = formattedDate.substring(formattedDate.indexOf(" de ") + 4, formattedDate.lastIndexOf(" de "));
        String yearPart = formattedDate.substring(formattedDate.lastIndexOf(" de ") + 4);

        // Capitalizar solo el día de la semana y el mes
        formattedDate = Character.toUpperCase(dayPart.charAt(0)) + dayPart.substring(1).toLowerCase() + " de "
                + Character.toUpperCase(monthPart.charAt(0)) + monthPart.substring(1).toLowerCase() + " de "
                + yearPart;

        // Establecer la fecha capitalizada en el header
        dateHeader.setText(formattedDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        inicio = new javax.swing.JButton();
        prestamos = new javax.swing.JButton();
        devoluciones = new javax.swing.JButton();
        usuarios = new javax.swing.JButton();
        libros = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        textHeader = new javax.swing.JLabel();
        dateHeader = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 640));

        background.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(14, 111, 159));
        menu.setPreferredSize(new java.awt.Dimension(270, 270));

        inicio.setBackground(new java.awt.Color(14, 150, 218));
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        inicio.setText("Inicio");
        inicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 40, 1, 1, new java.awt.Color(0, 0, 0)));
        inicio.setBorderPainted(false);
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inicio.setIconTextGap(15);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        prestamos.setBackground(new java.awt.Color(14, 150, 218));
        prestamos.setForeground(new java.awt.Color(255, 255, 255));
        prestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarminus.png"))); // NOI18N
        prestamos.setText("Préstamos");
        prestamos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 40, 1, 1, new java.awt.Color(0, 0, 0)));
        prestamos.setBorderPainted(false);
        prestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prestamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prestamos.setIconTextGap(15);
        prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamosActionPerformed(evt);
            }
        });

        devoluciones.setBackground(new java.awt.Color(14, 150, 218));
        devoluciones.setForeground(new java.awt.Color(255, 255, 255));
        devoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarplus.png"))); // NOI18N
        devoluciones.setText("Devoluciones");
        devoluciones.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 40, 1, 1, new java.awt.Color(0, 0, 0)));
        devoluciones.setBorderPainted(false);
        devoluciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        devoluciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        devoluciones.setIconTextGap(15);
        devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucionesActionPerformed(evt);
            }
        });

        usuarios.setBackground(new java.awt.Color(14, 150, 218));
        usuarios.setForeground(new java.awt.Color(255, 255, 255));
        usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        usuarios.setText("Usuarios");
        usuarios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 40, 1, 1, new java.awt.Color(0, 0, 0)));
        usuarios.setBorderPainted(false);
        usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuarios.setIconTextGap(15);
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });

        libros.setBackground(new java.awt.Color(14, 150, 218));
        libros.setForeground(new java.awt.Color(255, 255, 255));
        libros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        libros.setText("Libros");
        libros.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 40, 1, 1, new java.awt.Color(0, 0, 0)));
        libros.setBorderPainted(false);
        libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libros.setIconTextGap(15);
        libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosActionPerformed(evt);
            }
        });

        reportes.setBackground(new java.awt.Color(14, 150, 218));
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        reportes.setText("Reportes");
        reportes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 40, 1, 1, new java.awt.Color(0, 0, 0)));
        reportes.setBorderPainted(false);
        reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportes.setIconTextGap(15);
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(prestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(devoluciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(libros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(reportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libros, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(14, 150, 218));
        header.setPreferredSize(new java.awt.Dimension(750, 150));

        textHeader.setForeground(new java.awt.Color(255, 255, 255));
        textHeader.setText("Gestión de préstamos de biblioteca");

        dateHeader.setForeground(new java.awt.Color(255, 255, 255));
        dateHeader.setText("{dayname}, {day} de {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateHeader)
                    .addComponent(textHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(textHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(dateHeader)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(780, 430));
        content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        ShowJPanel(new Inicio());
    }//GEN-LAST:event_inicioActionPerformed

    private void prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamosActionPerformed
        ShowJPanel(new Prestamos());
    }//GEN-LAST:event_prestamosActionPerformed

    private void devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucionesActionPerformed
        ShowJPanel(new Devoluciones());
    }//GEN-LAST:event_devolucionesActionPerformed

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        ShowJPanel(new Usuarios());
    }//GEN-LAST:event_usuariosActionPerformed

    private void librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosActionPerformed
        ShowJPanel(new Libros());
    }//GEN-LAST:event_librosActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        ShowJPanel(new Reportes());
    }//GEN-LAST:event_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatCyanLightIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateHeader;
    private javax.swing.JButton devoluciones;
    private javax.swing.JPanel header;
    private javax.swing.JButton inicio;
    private javax.swing.JButton libros;
    private javax.swing.JPanel menu;
    private javax.swing.JButton prestamos;
    private javax.swing.JButton reportes;
    private javax.swing.JLabel textHeader;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
