/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author lizet
 */
public class NuevoUsuario extends javax.swing.JPanel {
    
    

    /**
     * Creates new form prestamos
     */
    public NuevoUsuario() {
        initComponents();
        InitStyles();
    }
    
   

    private void InitStyles() {
        //bienvenido.putClientProperty("FlatLaf.styleClass", "h2");
        title.putClientProperty("FlatLaf.style", "font: bold $h0.font");
        boleta.putClientProperty("FlatLaf.styleClass", "h2");
        tfboleta.putClientProperty("FlatLaf.styleClass", "h2");
        nombre.putClientProperty("FlatLaf.styleClass", "h2");
        tfnombre.putClientProperty("FlatLaf.styleClass", "h2");
        apaterno.putClientProperty("FlatLaf.styleClass", "h2");
        tfapaterno.putClientProperty("FlatLaf.styleClass", "h2");
        amaterno.putClientProperty("FlatLaf.styleClass", "h2");
        tfamaterno.putClientProperty("FlatLaf.styleClass", "h2");
        telefono.putClientProperty("FlatLaf.styleClass", "h2");
        tftelefono.putClientProperty("FlatLaf.styleClass", "h2");
        agregarusuario.putClientProperty("FlatLaf.styleClass", "h2");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        boleta = new javax.swing.JLabel();
        tfboleta = new javax.swing.JTextField();
        agregarusuario = new javax.swing.JButton();
        tfnombre = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        tfapaterno = new javax.swing.JTextField();
        tfamaterno = new javax.swing.JTextField();
        blank1 = new javax.swing.JLabel();
        apaterno = new javax.swing.JLabel();
        amaterno = new javax.swing.JLabel();
        blank2 = new javax.swing.JLabel();
        tftelefono = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(780, 430));
        setPreferredSize(new java.awt.Dimension(780, 430));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(780, 430));
        background.setPreferredSize(new java.awt.Dimension(780, 430));

        title.setText("Alta de usuario");

        boleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boleta.setText("Boleta");

        tfboleta.setToolTipText("");
        tfboleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfboletaActionPerformed(evt);
            }
        });

        agregarusuario.setBackground(new java.awt.Color(14, 111, 159));
        agregarusuario.setForeground(new java.awt.Color(255, 255, 255));
        agregarusuario.setText("Agregar usuario");
        agregarusuario.setBorderPainted(false);
        agregarusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarusuarioActionPerformed(evt);
            }
        });

        tfnombre.setToolTipText("");
        tfnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombreActionPerformed(evt);
            }
        });

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre");

        telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telefono.setText("Teléfono");

        tfapaterno.setToolTipText("");
        tfapaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfapaternoActionPerformed(evt);
            }
        });

        tfamaterno.setToolTipText("");
        tfamaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfamaternoActionPerformed(evt);
            }
        });

        blank1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        apaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apaterno.setText("Apellido Paterno");

        amaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amaterno.setText("Apellido Materno");

        blank2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tftelefono.setToolTipText("");
        tftelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(boleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(tfboleta)
                                .addGap(46, 46, 46))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(tfnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(tftelefono)
                                .addGap(45, 45, 45)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blank1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(apaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))
                                    .addComponent(amaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                                .addGap(17, 17, 17))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(tfapaterno))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(tfamaterno)
                                        .addGap(1, 1, 1)))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(blank2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(62, 62, 62)))))
                .addContainerGap())
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(agregarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(284, 284, 284))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfboleta)
                    .addComponent(tfapaterno))
                .addGap(22, 22, 22)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnombre)
                    .addComponent(tfamaterno))
                .addGap(25, 25, 25)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(blank1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blank2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tftelefono))
                .addGap(46, 46, 46)
                .addComponent(agregarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarusuarioActionPerformed

    private void tfboletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfboletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfboletaActionPerformed

    private void tfnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombreActionPerformed

    private void tfapaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfapaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfapaternoActionPerformed

    private void tfamaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfamaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfamaternoActionPerformed

    private void tftelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarusuario;
    private javax.swing.JLabel amaterno;
    private javax.swing.JLabel apaterno;
    private javax.swing.JPanel background;
    private javax.swing.JLabel blank1;
    private javax.swing.JLabel blank2;
    private javax.swing.JLabel boleta;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField tfamaterno;
    private javax.swing.JTextField tfapaterno;
    private javax.swing.JTextField tfboleta;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JTextField tftelefono;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
