/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author lizet
 */
public class NuevoLibro extends javax.swing.JPanel {
    
    

    /**
     * Creates new form prestamos
     */
    public NuevoLibro() {
        initComponents();
        InitStyles();
    }
    
   

    private void InitStyles() {
        //bienvenido.putClientProperty("FlatLaf.styleClass", "h2");
        title.putClientProperty("FlatLaf.style", "font: bold $h0.font");
        isbn.putClientProperty("FlatLaf.styleClass", "h2");
        tfisbn.putClientProperty("FlatLaf.styleClass", "h2");
        titulo.putClientProperty("FlatLaf.styleClass", "h2");
        tftitulo.putClientProperty("FlatLaf.styleClass", "h2");
        year.putClientProperty("FlatLaf.styleClass", "h2");
        tfyear.putClientProperty("FlatLaf.styleClass", "h2");
        pasillo.putClientProperty("FlatLaf.styleClass", "h2");
        tfpasillo.putClientProperty("FlatLaf.styleClass", "h2");
        autor.putClientProperty("FlatLaf.styleClass", "h2");
        tfautor.putClientProperty("FlatLaf.styleClass", "h2");
        agregarlibro.putClientProperty("FlatLaf.styleClass", "h2");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        tfisbn = new javax.swing.JTextField();
        agregarlibro = new javax.swing.JButton();
        tftitulo = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        autor = new javax.swing.JLabel();
        tfyear = new javax.swing.JTextField();
        tfpasillo = new javax.swing.JTextField();
        stock = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        pasillo = new javax.swing.JLabel();
        tfautor = new javax.swing.JTextField();
        tfstock = new javax.swing.JTextField();
        editorial = new javax.swing.JLabel();
        tfeditorial = new javax.swing.JTextField();
        blank3 = new javax.swing.JLabel();
        blank4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 430));
        setPreferredSize(new java.awt.Dimension(780, 430));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(780, 430));
        background.setPreferredSize(new java.awt.Dimension(780, 430));

        title.setText("Alta de libro");

        isbn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isbn.setText("ISBN");

        tfisbn.setToolTipText("");
        tfisbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfisbnActionPerformed(evt);
            }
        });

        agregarlibro.setBackground(new java.awt.Color(14, 111, 159));
        agregarlibro.setForeground(new java.awt.Color(255, 255, 255));
        agregarlibro.setText("Agregar libro");
        agregarlibro.setBorderPainted(false);
        agregarlibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarlibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarlibroActionPerformed(evt);
            }
        });

        tftitulo.setToolTipText("");
        tftitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftituloActionPerformed(evt);
            }
        });

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Título");

        autor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autor.setText("Autor");

        tfyear.setToolTipText("");
        tfyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfyearActionPerformed(evt);
            }
        });

        tfpasillo.setToolTipText("");
        tfpasillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpasilloActionPerformed(evt);
            }
        });

        stock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stock.setText("Stock");

        year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year.setText("Año");

        pasillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pasillo.setText("Pasillo");

        tfautor.setToolTipText("");
        tfautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfautorActionPerformed(evt);
            }
        });

        tfstock.setToolTipText("");
        tfstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstockActionPerformed(evt);
            }
        });

        editorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editorial.setText("Editorial");

        tfeditorial.setToolTipText("");
        tfeditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfeditorialActionPerformed(evt);
            }
        });

        blank3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        blank4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(autor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(isbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(tfisbn)
                                .addGap(46, 46, 46))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(tftitulo)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(tfautor)
                                .addGap(45, 45, 45)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))
                                    .addComponent(pasillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blank3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blank4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(17, 17, 17))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(tfyear))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(tfpasillo)
                                        .addGap(1, 1, 1)))
                                .addGap(60, 60, 60))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(tfstock)
                                .addGap(58, 58, 58)))))
                .addContainerGap())
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(agregarlibro, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(284, 284, 284))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(tfeditorial)
                        .addGap(46, 46, 46))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(424, 424, 424))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfisbn)
                    .addComponent(tfyear))
                .addGap(22, 22, 22)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pasillo, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftitulo)
                    .addComponent(tfpasillo))
                .addGap(25, 25, 25)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autor, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfautor)
                    .addComponent(tfstock))
                .addGap(29, 29, 29)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorial, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(blank3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfeditorial)
                    .addComponent(blank4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(agregarlibro, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarlibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarlibroActionPerformed

    private void tfisbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfisbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfisbnActionPerformed

    private void tftituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftituloActionPerformed

    private void tfyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfyearActionPerformed

    private void tfpasilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpasilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpasilloActionPerformed

    private void tfautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfautorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfautorActionPerformed

    private void tfstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfstockActionPerformed

    private void tfeditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfeditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfeditorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarlibro;
    private javax.swing.JLabel autor;
    private javax.swing.JPanel background;
    private javax.swing.JLabel blank3;
    private javax.swing.JLabel blank4;
    private javax.swing.JLabel editorial;
    private javax.swing.JLabel isbn;
    private javax.swing.JLabel pasillo;
    private javax.swing.JLabel stock;
    private javax.swing.JTextField tfautor;
    private javax.swing.JTextField tfeditorial;
    private javax.swing.JTextField tfisbn;
    private javax.swing.JTextField tfpasillo;
    private javax.swing.JTextField tfstock;
    private javax.swing.JTextField tftitulo;
    private javax.swing.JTextField tfyear;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
